<?php
/**
 * @package Mediboard\PlanningOp
 * @author  SAS OpenXtrem <dev@openxtrem.com>
 * @license https://www.gnu.org/licenses/gpl.html GNU General Public License
 * @license https://www.openxtrem.com/licenses/oxol.html OXOL OpenXtrem Open License
 */

$dPconfig["dPplanningOp"]= array(
  "COperation" => array (
    "mode_easy"          => "1col",
    "easy_materiel"      => "0",
    "easy_remarques"     => "0",
    "easy_regime"        => "1",
    "easy_accident"      => "0",
    "easy_assurances"    => "0",
    "easy_type_anesth"   => "0",
    "easy_length_input_label" => "50",
    "duree_deb"          => "0",
    "duree_fin"          => "10",
    "hour_urgence_deb"   => "0",
    "hour_urgence_fin"   => "23",
    "min_intervalle"     => "15",
    "locked"             => "0",
    "horaire_voulu"      => "0",
    "use_ccam"           => "1",
    "verif_cote"         => "0",
    "delete_only_admin"  => "1",
    "duree_preop_adulte" => "45",
    "duree_preop_enfant" => "15",
    "show_duree_preop"   => "0",
    "show_duree_uscpo"   => "0",
    "save_rank_annulee_validee" => "0",
    "cancel_only_for_resp_bloc" => "0",
    "fiche_examen"       => "0",
    "fiche_materiel"     => "0",
    "fiche_rques"        => "0",
    "nb_jours_urgence"   => "1",
    "use_poste"          => "0",
    "show_secondary_function" => "0",
    "show_presence_op"   => "1",
    "show_remarques"     => "1",
    "show_montant_dp"    => "1",
    "show_asa_position"  => "1",
    "show_print_dhe_info"  => "1",
    "default_week_stat_uscpo" => "last",
    "use_session_praticien" => true
   ),
  "CSejour" => array (
    "easy_cim10"          => "0",
    "easy_service"        => "0",
    "easy_uf_soins"       => "0",
    "easy_chambre_simple" => "1",
    "easy_ald_c2s"        => "0",
    "easy_atnc"           => "0",
    'easy_mode_sortie'    => '0',
    "easy_entree_sortie"  => "0",
    "patient_id"          => "1",
    "entree_modifiee"     => "1",
    "heure_deb"           => "0",
    "heure_fin"           => "23",
    "min_intervalle"      => "15",
    "locked"              => "0",
    "tag_dossier"         => "",
    "tag_dossier_group_idex"=> "",
    "tag_dossier_pa"      => "pa_",
    "tag_dossier_cancel"  => "cancel_",
    "tag_dossier_trash"   => "trash_",
    "tag_dossier_rang"    => "",
    "use_dossier_rang"    => "0",
    "blocage_occupation"  => "0",
    "service_id_notNull"  => "0",
    "consult_accomp"      => "0",
    "delete_only_admin"   => "1",
    "max_cancel_time"     => "0",
    "hours_sejour_proche" => "48",
    "show_modal_identifiant"    => "0",
    "show_discipline_tarifaire" => "0",
    "show_type_pec" => "0",
    "create_anonymous_pat" => "0",
    "anonymous_sexe" => "m",
    "anonymous_naissance" => "1970-12-31",
    "use_recuse" => "0",
    "systeme_isolement"  => "standard",
    "easy_isolement"     => "0",

    "show_only_charge_price_indicator" => "0",
    "use_custom_mode_entree" => "0",
    "use_custom_mode_sortie" => "0",
    "specified_output_mode"  => "1",

    "show_confirm_change_patient" => "1",
    'use_session_praticien' => '0'
  ),
  'CPatient' => array(
    'easy_correspondant'  => '0',
    'easy_tutelle'        => '0',
    'easy_handicap'       => '0',
    'easy_aide_organisee' => '0',
  ),
  "CRegleSectorisation" => array (
    "use_sectorisation"   =>  "0",
  ),
);
