CREATE TABLE IF NOT EXISTS `diplome_autorisation_exercice`
(
    `type_identifiant`                 INT(1) UNSIGNED NOT NULL,
    `identifiant`                      VARCHAR(11)     NOT NULL,
    `identifiant_national`             VARCHAR(12)     NOT NULL,
    `nom`                              VARCHAR(50)     NOT NULL,
    `prenom`                           VARCHAR(50)     NOT NULL,
    `code_type_diplome`                VARCHAR(5),
    `libelle_type_diplome`             VARCHAR(50),
    `code_diplome`                     VARCHAR(5),
    `libelle_diplome`                  VARCHAR(100),
    `code_type_autorisation`           VARCHAR(10),
    `libelle_type_autorisation`        VARCHAR(100),
    `code_discipline_autorisation`     VARCHAR(10),
    `libelle_discipline_autorisation`  VARCHAR(50),
    `version`                          VARCHAR(10)     NOT NULL,
    `synchronized`                     ENUM ('0', '1') DEFAULT '0',
    `error`                            ENUM ('0', '1') DEFAULT '0',
    `diplome_autorisation_exercice_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    INDEX `type_identifiant` (`type_identifiant`),
    INDEX `identifiant` (`identifiant`),
    INDEX `identifiant_national` (`identifiant_national`),
    INDEX `code_type_diplome` (`code_type_diplome`),
    INDEX `code_diplome` (`code_diplome`),
    INDEX `version` (`version`),
    INDEX `synchronized` (`synchronized`)
) ENGINE = MyISAM;

CREATE TABLE IF NOT EXISTS `savoir_faire`
(
    `type_identifiant`          INT(1) UNSIGNED NOT NULL,
    `identifiant`               VARCHAR(11)     NOT NULL,
    `identifiant_national`      VARCHAR(12)     NOT NULL,
    `nom`                       VARCHAR(50)     NOT NULL,
    `prenom`                    VARCHAR(50)     NOT NULL,
    `code_profession`           INT(2) UNSIGNED NOT NULL,
    `libelle_profession`        VARCHAR(50)     NOT NULL,
    `code_categorie_pro`        VARCHAR(1),
    `libelle_categorie_pro`     VARCHAR(50),
    `code_type_savoir_faire`    VARCHAR(10),
    `libelle_type_savoir_faire` VARCHAR(50),
    `code_savoir_faire`         VARCHAR(10),
    `libelle_savoir_faire`      VARCHAR(100),
    `version`                   VARCHAR(10)     NOT NULL,
    `synchronized`              ENUM ('0', '1') DEFAULT '0',
    `error`                     ENUM ('0', '1') DEFAULT '0',
    `savoir_faire_id`           INT(11) PRIMARY KEY AUTO_INCREMENT,
    INDEX `type_identifiant` (`type_identifiant`),
    INDEX `identifiant` (`identifiant`),
    INDEX `identifiant_national` (`identifiant_national`),
    INDEX `code_profession` (`code_profession`),
    INDEX `version` (`version`),
    INDEX `synchronized` (`synchronized`)
) ENGINE = MyISAM;

CREATE TABLE IF NOT EXISTS `personne_exercice`
(
    `type_identifiant`               INT(1) UNSIGNED NOT NULL,
    `identifiant`                    VARCHAR(11)     NOT NULL,
    `identifiant_national`           VARCHAR(12)     NOT NULL,
    `code_civilite_exercice`         VARCHAR(5),
    `libelle_civilite_exercice`      VARCHAR(50),
    `code_civilite`                  VARCHAR(5),
    `libelle_civilite`               VARCHAR(50),
    `nom`                            VARCHAR(50),
    `prenom`                         VARCHAR(50),
    `code_profession`                INT(2) UNSIGNED NOT NULL,
    `libelle_profession`             VARCHAR(50)     NOT NULL,
    `code_cat_pro`                   VARCHAR(5),
    `libelle_cat_pro`                VARCHAR(50),
    `code_type_savoir_faire`         VARCHAR(5),
    `libelle_type_savoir_faire`      VARCHAR(50),
    `code_savoir_faire`              VARCHAR(5),
    `libelle_savoir_faire`           VARCHAR(100),
    `code_mode_exercice`             VARCHAR(1),
    `libelle_mode_exercice`          VARCHAR(8),
    `siret_site`                     VARCHAR(14),
    `siren_site`                     VARCHAR(9),
    `finess_site`                    VARCHAR(9),
    `finess_etab_juridique`          VARCHAR(9),
    `id_technique_structure`         VARCHAR(50),
    `raison_sociale_site`            VARCHAR(255),
    `enseigne_comm_site`             VARCHAR(100),
    `comp_destinataire`              VARCHAR(50),
    `comp_point_geo`                 VARCHAR(50),
    `num_voie`                       VARCHAR(4),
    `repetition_voie`                VARCHAR(3),
    `code_type_voie`                 VARCHAR(5),
    `libelle_type_voie`              VARCHAR(50),
    `libelle_voie`                   VARCHAR(50),
    `mention_distrib`                VARCHAR(50),
    `cedex`                          VARCHAR(50),
    `cp`                             VARCHAR(5),
    `code_commune`                   VARCHAR(5),
    `libelle_commune`                VARCHAR(50),
    `code_pays`                      VARCHAR(5),
    `libelle_pays`                   VARCHAR(10),
    `tel`                            VARCHAR(15),
    `tel2`                           VARCHAR(15),
    `fax`                            VARCHAR(15),
    `email`                          VARCHAR(100),
    `code_departement`               VARCHAR(50),
    `libelle_departement`            VARCHAR(50),
    `ancien_id_structure`            VARCHAR(50),
    `autorite_enregistrement`        VARCHAR(50),
    `code_secteur_activite`          VARCHAR(4),
    `libelle_secteur_activite`       VARCHAR(100),
    `code_section_tableau_pharma`    VARCHAR(2),
    `libelle_section_tableau_pharma` VARCHAR(255),
    `version`                        VARCHAR(10)     NOT NULL,
    `synchronized`                   ENUM ('0', '1') DEFAULT '0',
    `error`                          ENUM ('0', '1') DEFAULT '0',
    `personne_exercice_id`           INT(11) PRIMARY KEY AUTO_INCREMENT,
    INDEX `type_identifiant` (`type_identifiant`),
    INDEX `identifiant` (`identifiant`),
    INDEX `identifiant_national` (`identifiant_national`),
    INDEX `nom` (`nom`),
    INDEX `prenom` (`prenom`),
    INDEX `code_profession` (`code_profession`),
    INDEX `cp` (`cp`),
    INDEX `version` (`version`),
    INDEX `synchronized` (`synchronized`),
    INDEX `error` (`error`),
    INDEX `sync_error` (`synchronized`, `error`)
) ENGINE = MyISAM;

CREATE TABLE IF NOT EXISTS `mssante_info`
(
    `type_bal`                          ENUM ('PER', 'ORG') NOT NULL,
    `email`                             VARCHAR(100)        NOT NULL,
    `type_identifiant`                  INT(1)              NOT NULL,
    `identifiant`                       VARCHAR(11)         NOT NULL,
    `identifiant_national`              VARCHAR(12)         NOT NULL,
    `type_id_structure`                 INT(1),
    `id_structure`                      VARCHAR(20),
    `service_rattachement`              VARCHAR(80),
    `civilite`                          VARCHAR(20),
    `nom`                               VARCHAR(80),
    `prenom`                            VARCHAR(80),
    `categorie_profession`              INT(1),
    `libelle_categorie_profession`      VARCHAR(50),
    `code_profession`                   INT(2),
    `libelle_profession`                VARCHAR(20),
    `code_savoir_faire`                 VARCHAR(5),
    `libelle_savoir_faire`              VARCHAR(50),
    `dematerialisation`                 ENUM ('O', 'N'),
    `raison_sociale_bal`                VARCHAR(50),
    `enseigne_commerciale_structure`    VARCHAR(100),
    `complement_localisation_structure` VARCHAR(100),
    `complement_distribution_structure` VARCHAR(100),
    `numero_voie_structure`             VARCHAR(4),
    `complement_numero_voie_structure`  VARCHAR(100),
    `type_voie_structure`               VARCHAR(20),
    `libelle_voie_structure`            VARCHAR(100),
    `lieu_dit_mention_structure`        VARCHAR(100),
    `ligne_acheminement_structure`      VARCHAR(100),
    `code_postal_structure`             VARCHAR(5),
    `departement_structure`             VARCHAR(100),
    `pays_structure`                    VARCHAR(100),
    `version`                           VARCHAR(10)         NOT NULL,
    `synchronized`                      ENUM ('0', '1') DEFAULT '0',
    `error`                             ENUM ('0', '1') DEFAULT '0',
    `mssante_info_id`                   INT(11) PRIMARY KEY AUTO_INCREMENT,
    INDEX `type_identifiant` (`type_identifiant`),
    INDEX `type_bal` (`type_bal`),
    INDEX `identifiant` (`identifiant`),
    INDEX `identifiant_national` (`identifiant_national`),
    INDEX `version` (`version`),
    INDEX `synchronized` (`synchronized`),
    INDEX `error` (`error`),
    INDEX `id_structure` (`id_structure`)
) ENGINE = MyISAM;
